# Generated by Django 3.1.2 on 2020-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tiki', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('thumnail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tiki', models.IntegerField()),
                ('rating_average', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('book_cover', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bookdetail',
                'managed': False,
            },
        ),
    ]
