# Generated by Django 3.0.5 on 2020-11-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_userclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabFilteringRsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tiki', models.IntegerField()),
                ('rs1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSimilarityBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tiki', models.IntegerField()),
                ('title_similarity', models.CharField(max_length=255)),
                ('descript_similarity', models.CharField(max_length=255)),
            ],
        ),
    ]
